services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Keep DB private on the Docker network (safer).
    # Uncomment the next lines temporarily if you want to connect from a host GUI client:
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${API_PORT:-3000}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      # live-edit backend code from WSL filesystem
      - ./backend:/app:rw,delegated
      - /app/node_modules
    command: ["node", "server.js"]  # or ["npm","run","dev"] if you prefer hot reload
    restart: unless-stopped

volumes:
  pgdata:
